### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error

### ISSUE THREAD

**Issue by binkelderg** [WP2Static/wp2static-addon-netlify#7]
> Fatal error: Uncaught Error: Class 'WP2StaticNetlify\Controller' not found in C:\wordpress\apps\wordpress\htdocs\wp-content\plugins\wp2static-addon-netlify-master\wp2static-addon-netlify.php:27 Stack trace: #0 C:\wordpress\apps\wordpress\htdocs\wp-content\plugins\wp2static-addon-netlify-master\wp2static-addon-netlify.php(41): run_wp2static_addon_netlify() #1 C:\wordpress\apps\wordpress\htdocs\wp-admin\includes\plugin.php(2286): include_once('C:\\wordpress\\ap...') #2 C:\wordpress\apps\wordpress\htdocs\wp-admin\plugins.php(191): plugin_sandbox_scrape() #3 {main} thrown in C:\wordpress\apps\wordpress\htdocs\wp-content\plugins\wp2static-addon-netlify-master\wp2static-addon-netlify.php on line 27

**Comment by binkelderg** [comment]
Fixed it with the compiler uploaded in #6. Most download links aren't working right anymore it seems.

**Comment by binkelderg** [comment]
Fixed it with the compiler uploaded in #6. Most download links aren't working right anymore it seems.
